---
abstract: 'Add infobot features to an PoCo-IRC'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  Test::MockObject: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POE-Component-IRC-Plugin-Infobot
no_index:
  directory:
    - t
    - inc
requires:
  DB_File: '0'
  IRC::Utils: '0.12'
  POE::Component::IRC::Plugin: '0'
  perl: '5.014000'
resources:
  repository: http://git.ieval.ro/?p=poe-component-irc-plugin-infobot.git
version: '0.001002'
